CLASSES = [
	"pizza",
	"burger",
	"dosa",
	"rice",
	"salad",
	"icecream",
	"biriyani",
	"pasta",
	"noodles",
	"chicken",
	"fish",
	"fries",
	"sandwich",
	"taco",
	"samosa",
	"momos",
	"paneer",
	"tandoori_chicken",
	"sushi",
	"steak",
	"cake",
	"waffle",
	"oats",
	"nuts",
]

INGREDIENTS = {
	"pizza": [
		{"name": "pizza base", "calories": 180},
		{"name": "cheese", "calories": 80},
		{"name": "tomato sauce", "calories": 20},
		{"name": "vegetables", "calories": 40},
	],
	"burger": [
		{"name": "bun", "calories": 140},
		{"name": "patty", "calories": 120},
		{"name": "cheese", "calories": 70},
		{"name": "lettuce and sauce", "calories": 40},
	],
	"dosa": [
		{"name": "dosa batter", "calories": 140},
		{"name": "oil", "calories": 25},
		{"name": "sambar", "calories": 30},
		{"name": "chutney", "calories": 25},
	],
	"rice": [
		{"name": "cooked rice", "calories": 130},
	],
	"salad": [
		{"name": "leafy vegetables", "calories": 20},
		{"name": "tomato", "calories": 10},
		{"name": "cucumber", "calories": 10},
		{"name": "dressing", "calories": 40},
	],
	"icecream": [
		{"name": "milk", "calories": 110},
		{"name": "sugar", "calories": 70},
		{"name": "cream", "calories": 27},
	],
	"biriyani": [
		{"name": "rice", "calories": 180},
		{"name": "meat or vegetables", "calories": 70},
		{"name": "oil and spices", "calories": 40},
	],
	"pasta": [
		{"name": "pasta", "calories": 150},
		{"name": "pasta sauce", "calories": 60},
		{"name": "cheese", "calories": 80},
		{"name": "olive oil", "calories": 35},
	],
	"noodles": [
		{"name": "noodles", "calories": 130},
		{"name": "broth", "calories": 25},
		{"name": "vegetables", "calories": 40},
		{"name": "soy sauce", "calories": 15},
	],
	"chicken": [
		{"name": "grilled chicken", "calories": 165},
		{"name": "lemon and herbs", "calories": 20},
		{"name": "oil", "calories": 30},
	],
	"fish": [
		{"name": "fish fillet", "calories": 155},
		{"name": "lemon", "calories": 10},
		{"name": "herbs", "calories": 5},
		{"name": "oil", "calories": 25},
	],
	"fries": [
		{"name": "potato", "calories": 110},
		{"name": "cooking oil", "calories": 60},
		{"name": "salt", "calories": 0},
	],
	"sandwich": [
		{"name": "bread", "calories": 140},
		{"name": "fillings (meat/cheese)", "calories": 100},
		{"name": "vegetables", "calories": 30},
		{"name": "sauce", "calories": 35},
	],
	"taco": [
		{"name": "tortilla", "calories": 95},
		{"name": "meat", "calories": 90},
		{"name": "salsa", "calories": 20},
		{"name": "cheese and toppings", "calories": 60},
	],
	"samosa": [
		{"name": "pastry", "calories": 120},
		{"name": "potato filling", "calories": 60},
		{"name": "peas and spices", "calories": 25},
		{"name": "oil", "calories": 40},
	],
	"momos": [
		{"name": "dough wrapper", "calories": 80},
		{"name": "meat or vegetable filling", "calories": 65},
		{"name": "spices and oil", "calories": 25},
	],
	"paneer": [
		{"name": "paneer cheese", "calories": 140},
		{"name": "spices", "calories": 15},
		{"name": "cream sauce", "calories": 50},
		{"name": "oil", "calories": 35},
	],
	"tandoori_chicken": [
		{"name": "chicken", "calories": 165},
		{"name": "yogurt marinade", "calories": 30},
		{"name": "tandoori spices", "calories": 20},
		{"name": "oil", "calories": 25},
	],
	"sushi": [
		{"name": "rice", "calories": 110},
		{"name": "fish or seafood", "calories": 80},
		{"name": "nori seaweed", "calories": 10},
		{"name": "vegetables", "calories": 20},
	],
	"steak": [
		{"name": "beef steak", "calories": 250},
		{"name": "butter", "calories": 35},
		{"name": "salt and pepper", "calories": 0},
	],
	"cake": [
		{"name": "cake base", "calories": 180},
		{"name": "frosting", "calories": 100},
		{"name": "decorations", "calories": 20},
	],
	"waffle": [
		{"name": "waffle", "calories": 140},
		{"name": "syrup", "calories": 80},
		{"name": "butter", "calories": 35},
		{"name": "whipped cream", "calories": 25},
	],
	"oats": [
		{"name": "oatmeal", "calories": 90},
		{"name": "milk", "calories": 75},
		{"name": "honey or sugar", "calories": 60},
		{"name": "fruits and nuts", "calories": 50},
	],
	"nuts": [
		{"name": "almonds", "calories": 95},
		{"name": "cashews", "calories": 90},
		{"name": "walnuts", "calories": 98},
		{"name": "peanuts", "calories": 85},
	],
}

CALORIES = {food: sum(item["calories"] for item in ingredients) for food, ingredients in INGREDIENTS.items()}
INGREDIENT_CALORIES = {}
for _food, _ingredients in INGREDIENTS.items():
	for _item in _ingredients:
		name = _item["name"]
		INGREDIENT_CALORIES[name] = max(INGREDIENT_CALORIES.get(name, 0), _item["calories"])

# Nutrition values are approximate per serving used by this project.
NUTRITION_DB = {
	"pizza base": {"calories": 180, "protein": 6.0, "carbs": 34.0, "fat": 4.0},
	"cheese": {"calories": 80, "protein": 5.0, "carbs": 1.0, "fat": 6.0},
	"tomato sauce": {"calories": 20, "protein": 0.7, "carbs": 4.0, "fat": 0.1},
	"vegetables": {"calories": 40, "protein": 1.5, "carbs": 8.0, "fat": 0.3},
	"bun": {"calories": 140, "protein": 4.0, "carbs": 26.0, "fat": 2.0},
	"patty": {"calories": 120, "protein": 11.0, "carbs": 3.0, "fat": 7.0},
	"lettuce and sauce": {"calories": 40, "protein": 0.8, "carbs": 4.0, "fat": 2.2},
	"dosa batter": {"calories": 140, "protein": 3.0, "carbs": 24.0, "fat": 3.0},
	"oil": {"calories": 25, "protein": 0.0, "carbs": 0.0, "fat": 2.8},
	"sambar": {"calories": 30, "protein": 1.2, "carbs": 4.0, "fat": 0.9},
	"chutney": {"calories": 25, "protein": 0.5, "carbs": 2.0, "fat": 1.8},
	"cooked rice": {"calories": 130, "protein": 2.4, "carbs": 28.0, "fat": 0.3},
	"leafy vegetables": {"calories": 20, "protein": 1.5, "carbs": 3.0, "fat": 0.2},
	"tomato": {"calories": 10, "protein": 0.4, "carbs": 2.2, "fat": 0.1},
	"cucumber": {"calories": 10, "protein": 0.3, "carbs": 1.8, "fat": 0.1},
	"dressing": {"calories": 40, "protein": 0.2, "carbs": 3.0, "fat": 3.0},
	"milk": {"calories": 110, "protein": 5.8, "carbs": 8.0, "fat": 6.0},
	"sugar": {"calories": 70, "protein": 0.0, "carbs": 18.0, "fat": 0.0},
	"cream": {"calories": 27, "protein": 0.2, "carbs": 0.6, "fat": 2.8},
	"rice": {"calories": 180, "protein": 3.2, "carbs": 40.0, "fat": 0.4},
	"meat or vegetables": {"calories": 70, "protein": 5.0, "carbs": 3.0, "fat": 4.0},
	"oil and spices": {"calories": 40, "protein": 0.5, "carbs": 2.0, "fat": 3.5},
	"onion": {"calories": 16, "protein": 0.4, "carbs": 3.7, "fat": 0.0},
	"ginger": {"calories": 8, "protein": 0.2, "carbs": 1.8, "fat": 0.1},
	"garlic": {"calories": 10, "protein": 0.5, "carbs": 2.3, "fat": 0.0},
	"chili": {"calories": 6, "protein": 0.3, "carbs": 1.3, "fat": 0.1},
	"turmeric": {"calories": 8, "protein": 0.2, "carbs": 1.4, "fat": 0.1},
	"coriander": {"calories": 5, "protein": 0.4, "carbs": 0.9, "fat": 0.1},
	"salt": {"calories": 0, "protein": 0.0, "carbs": 0.0, "fat": 0.0},
	"black pepper": {"calories": 3, "protein": 0.1, "carbs": 0.7, "fat": 0.0},
	"carrot": {"calories": 12, "protein": 0.3, "carbs": 2.8, "fat": 0.1},
	"pasta": {"calories": 150, "protein": 5.0, "carbs": 30.0, "fat": 1.0},
	"pasta sauce": {"calories": 60, "protein": 1.5, "carbs": 8.0, "fat": 2.5},
	"olive oil": {"calories": 35, "protein": 0.0, "carbs": 0.0, "fat": 3.9},
	"noodles": {"calories": 130, "protein": 3.5, "carbs": 25.0, "fat": 1.5},
	"broth": {"calories": 25, "protein": 2.0, "carbs": 3.0, "fat": 0.5},
	"soy sauce": {"calories": 15, "protein": 2.0, "carbs": 1.5, "fat": 0.0},
	"grilled chicken": {"calories": 165, "protein": 31.0, "carbs": 0.0, "fat": 3.6},
	"fish fillet": {"calories": 155, "protein": 26.0, "carbs": 0.0, "fat": 5.0},
	"potato": {"calories": 110, "protein": 2.0, "carbs": 26.0, "fat": 0.1},
	"cooking oil": {"calories": 60, "protein": 0.0, "carbs": 0.0, "fat": 6.7},
	"bread": {"calories": 140, "protein": 4.0, "carbs": 27.0, "fat": 1.5},
	"fillings (meat/cheese)": {"calories": 100, "protein": 8.0, "carbs": 2.0, "fat": 6.0},
	"tortilla": {"calories": 95, "protein": 2.5, "carbs": 17.0, "fat": 1.5},
	"meat": {"calories": 90, "protein": 14.0, "carbs": 0.0, "fat": 3.5},
	"salsa": {"calories": 20, "protein": 0.5, "carbs": 4.0, "fat": 0.1},
	"cheese and toppings": {"calories": 60, "protein": 4.0, "carbs": 2.0, "fat": 4.5},
	"pastry": {"calories": 120, "protein": 2.5, "carbs": 16.0, "fat": 5.0},
	"potato filling": {"calories": 60, "protein": 1.5, "carbs": 13.0, "fat": 0.3},
	"peas and spices": {"calories": 25, "protein": 1.5, "carbs": 4.0, "fat": 0.3},
	"dough wrapper": {"calories": 80, "protein": 3.0, "carbs": 15.0, "fat": 0.5},
	"meat or vegetable filling": {"calories": 65, "protein": 6.0, "carbs": 4.0, "fat": 2.5},
	"spices and oil": {"calories": 25, "protein": 0.5, "carbs": 2.0, "fat": 1.5},
	"paneer cheese": {"calories": 140, "protein": 14.0, "carbs": 1.0, "fat": 8.0},
	"cream sauce": {"calories": 50, "protein": 1.5, "carbs": 2.0, "fat": 4.0},
	"yogurt marinade": {"calories": 30, "protein": 3.0, "carbs": 2.0, "fat": 1.0},
	"tandoori spices": {"calories": 20, "protein": 1.0, "carbs": 3.0, "fat": 0.5},
	"rice": {"calories": 110, "protein": 2.0, "carbs": 24.0, "fat": 0.2},
	"fish or seafood": {"calories": 80, "protein": 15.0, "carbs": 0.0, "fat": 1.0},
	"nori seaweed": {"calories": 10, "protein": 1.5, "carbs": 1.0, "fat": 0.2},
	"beef steak": {"calories": 250, "protein": 26.0, "carbs": 0.0, "fat": 15.0},
	"butter": {"calories": 35, "protein": 0.0, "carbs": 0.0, "fat": 3.9},
	"cake base": {"calories": 180, "protein": 2.5, "carbs": 24.0, "fat": 8.0},
	"frosting": {"calories": 100, "protein": 0.5, "carbs": 16.0, "fat": 4.0},
	"decorations": {"calories": 20, "protein": 0.0, "carbs": 5.0, "fat": 0.0},
	"almonds": {"calories": 95, "protein": 3.5, "carbs": 3.5, "fat": 8.2},
	"cashews": {"calories": 90, "protein": 3.0, "carbs": 5.0, "fat": 7.5},
	"walnuts": {"calories": 98, "protein": 2.3, "carbs": 2.0, "fat": 9.5},
	"peanuts": {"calories": 85, "protein": 3.5, "carbs": 3.0, "fat": 7.0},

	"waffle": {"calories": 140, "protein": 3.0, "carbs": 18.0, "fat": 5.0},
	"syrup": {"calories": 80, "protein": 0.0, "carbs": 21.0, "fat": 0.0},
	"whipped cream": {"calories": 25, "protein": 0.2, "carbs": 1.0, "fat": 2.5},
	"oatmeal": {"calories": 90, "protein": 2.7, "carbs": 16.0, "fat": 1.5},
	"honey or sugar": {"calories": 60, "protein": 0.0, "carbs": 16.0, "fat": 0.0},
	"fruits and nuts": {"calories": 50, "protein": 1.5, "carbs": 8.0, "fat": 1.5},}

CONFIDENCE_THRESHOLD = 0.6
INGREDIENT_CONFIDENCE_THRESHOLD = 0.5
ALLOWED_IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}
MAX_IMAGE_SIZE_BYTES = 8 * 1024 * 1024
CACHE_TTL_SECONDS = 300
